directories:
  logging: log
  rules: rules
  lib: lib
  params: parameters
  config: config

location:
  latitude: 52.5185537
  longitude: 13.3758636
  elevation: 43

mqtt:
  connection:
    identifier: HABAppTesting
    host: mosquitto
    user: ''
    password: ''
    port: 1883
    tls:
      enabled: false
      insecure: false
      ca cert: ''
  publish:
    qos: 0
    retain: false
  subscribe:
    qos: 0
    topics:
    - '#'
  general:
    listen_only: false

openhab:
  connection:
    url: http://openhab:8080   # Connect to this url
    user: ''
    password: ''
    verify_ssl: true             # Check certificates when using https
  general:
    listen_only: false
    wait_for_openhab: false
  ping:
    enabled: false
    interval: 30
    item: Ping
